### ISSUE TITLE
[Pulsar-doc search] The search does not work for Pulsar 2.7.0 release 

### ISSUE THREAD

**Issue by Jennifer88huang** [algolia/docsearch-configs#2994]
# Report a **bug**

## What is the **current** behaviour?
In #2980, I've added the "2.7.0" and "2.6.2" versions in the config file, yet the search does not work for "2.7.0". It works for 2.6.2 version. The following is screenshot from 2.7.0 search on Pulsar doc website http://pulsar.apache.org/docs/en/standalone/
![image](https://user-images.githubusercontent.com/47805623/101284264-0c346e80-381a-11eb-8575-1e2d5be2c6bb.png)

## What is the **expected** behaviour?
The search should work for 2.7.0 version.

#### What have you tried to solve it?
Try to fix it in #2980

**Comment by shortcuts** [comment]
Solved in https://github.com/algolia/docsearch-configs/pull/3005

**Comment by Jennifer88huang** [comment]
@shortcuts It seems that the current solution still does not work for Pulsar 2.7.0 and other versions (except the "next") http://pulsar.apache.org/docs/en/standalone/
Could you please help double check? Thank you very much.
![image](https://user-images.githubusercontent.com/47805623/101721850-dcb88700-3ae3-11eb-87af-5bd87955861b.png)

![image](https://user-images.githubusercontent.com/47805623/101721818-c8748a00-3ae3-11eb-8272-fc482604edec.png)

![image](https://user-images.githubusercontent.com/47805623/101721874-f1951a80-3ae3-11eb-9ddb-ca8c445c833e.png)

**Comment by Jennifer88huang** [comment]
Could you please open this issue? Thank you.

**Comment by shortcuts** [comment]
Hi @Jennifer88huang,

It looks like somehow the crawl was stalled, I just ran it again and it worked with more than 700k hits returned and every versions available. 

Pushing it in: https://github.com/algolia/docsearch-configs/pull/3014

Let's hope this solves your issue!

Have a nice day

**Comment by shortcuts** [comment]
Hey @Jennifer88huang,

The tasks just finished and it looks like it's working!

**Comment by Jennifer88huang** [comment]
@shortcuts cool, it works now.
Thank you very much for your help and support~
