### ISSUE TITLE
[appvia] Missing results for query "AWS"

### ISSUE THREAD

**Issue by KashifSaadat** [algolia/docsearch-configs#3460]
I can't get results for any search term on my site: https://docs.appvia.io/

Currently 'docusaurus-lunr-search' is in use on the production site whilst I validate locally (using Algolia Search), with the production site being indexed. I have used the configuration precisely as defined in the Docusuarus docs (https://v2.docusaurus.io/docs/search#connecting-algolia), so suspect there could be misconfiguration in the [appvia.json](https://github.com/algolia/docsearch-configs/blob/master/configs/appvia.json) config?

**Comment by shortcuts** [comment]
Hi,

It looks like has been resolved, feel free to re-open if that's not the case.

**Comment by KashifSaadat** [comment]
Hi @shortcuts, I'm still not receiving any results unfortunately. Please can you re-open the issue?

**Comment by shortcuts** [comment]
Hi @KashifSaadat,

Could you please give more informations about what's missing?

When I search `AWS` or any other query on `https://docs.appvia.io/` it works as expected on my side.

**Comment by KashifSaadat** [comment]
I've removed the Algolia Search plugin from `docs.appvia.io` at the moment because it wasn't working. So currently the site is using local search (docusaurus-lunr-search).

I am testing identical plugin configuration against the `docs.appvia.io` index with a local instance, which returns no results.

**Comment by shortcuts** [comment]
Hi @KashifSaadat,

Is there any news on your side? Could you please copy your `docusaurus.config.js` (only the `algolia` part) to see if there's any issue with the instance?

Everything works as expected on our side.

**Comment by KashifSaadat** [comment]
Hi @shortcuts, no luck yet I'm afraid, it still displays no results in my test instance with the algolia configuration.

The config is as follows (within `themeConfig`):
```
    algolia: {
      apiKey: 'd468bdf50335c77476fa8e3331cf7db4',
      indexName: 'appvia',
      contextualSearch: true,
    },
```

**Comment by shortcuts** [comment]
Would you be able to deploy it on netlify to see what the query returns?

From what I'm seeing, everything seems ok ([codesandbox](https://codesandbox.io/s/beautiful-keldysh-89h0m)).

**Comment by KashifSaadat** [comment]
Just deployed it here: https://epic-heyrovsky-36fbaa.netlify.app/kore/

I compared the queries between your example and my deployment and noticed the following included on the query (when I have `Latest` version selected): `facetFilters: ["language:en",["docusaurus_tag:default","docusaurus_tag:docs-kore-current"]]`

If I exclude that manually from a curl command I get results, so it seems to be related to the filter on doc tags. I'm not sure why this is or how to resolve, do you have any advice? There's currently the following published:
- latest (unversioned but default docs)
- 0.6 (versioned and old documentation)

**Comment by shortcuts** [comment]
This is related to the `contextual search` option that will append the value of the corresponding `meta` tags. 

Your netlify site have these meta tags (see in `<head>`) but not your production site, so when we crawl it, we can't retrieve these informations. Which is why when submitting a query with these `facetFilters`, our engine returns zero results.

**Comment by KashifSaadat** [comment]
Thank you! So I see that after enabling Algolia (including the config in `docusaurus.config.js`), one of the meta tags change from `docusaurus_tag` to `docsearch:docusaurus_tag`.

I will configure this in Production with `contextualSearch` disabled for now, and once the site has been re-indexed it should work as expected.

Thanks for your help!

**Comment by shortcuts** [comment]
Feel free to @ me if there's any other issue, I'll close this for the moment!
