### ISSUE TITLE
[mediamachine] Missing results for query "thumbnail"

### ISSUE THREAD

**Issue by urjitbhatia** [algolia/docsearch-configs#3635]
We are seeing pretty much 0 coverage on any keyword

**Comment by shortcuts** [comment]
Hi,

Fixed this in https://github.com/algolia/docsearch-configs/pull/3639, you should see the changes in the next 24 hours.

**Comment by urjitbhatia** [comment]
Hi @shortcuts we are sadly still not seeing this. Anything you can double check?

**Comment by shortcuts** [comment]
Hi @urjitbhatia, this happen because you are sending these `facetFilters` `["language:en",["docusaurus_tag:default","docusaurus_tag:docs-default-current"]]"}]}` in your query with the [contextual search](https://v2.docusaurus.io/docs/search#contextual-search) option.

As the `meta tags` (`<meta data-react-helmet="true" name="docsearch:language" content="en">` etc.) are not defined on your site, you can't use them as `facetFilters`.

You can either remove the `contextualSearch` option or add the meta tags to your site, both will solve your issue!

**Comment by urjitbhatia** [comment]
Thanks a lot @shortcuts - that was it. Got it to work
