### ISSUE TITLE
[sprinklr_spaceweb] Missing results for query "cheatsheet"

### ISSUE THREAD

**Issue by ujjawalpabreja99** [algolia/docsearch-configs#4660]
Queries bear no/irrelevant results ("cheatsheet" is just an example). Only a handful are able to get the desired results for us. 
Would be grateful if someone could look into our index and check if everything's updated correctly. 
Thanks!

**Comment by shortcuts** [comment]
Hey @ujjawalpabreja99, I've pushed an update in the above PR, I'd still recommend you to check ours tips for better searches: https://docsearch.algolia.com/docs/tips and make sure your config suits you :)

**Comment by ujjawalpabreja99** [comment]
Hey @shortcuts. Thanks for the quick update, and for sharing the tips! 
Unfortunately, we are still getting the same results as earlier. Can you please confirm if the scraper has successfully updated our index as per the new config file? I read it runs every 24 hours.

**Comment by shortcuts** [comment]
Hey @ujjawalpabreja99, it ran right after the PR merge and ran again an hour ago!

**Comment by ujjawalpabreja99** [comment]
Hi @shortcuts 
I have added a sitemap to our config file. I am hopeful that this is a potential fix for our search results. Please review the [PR](https://github.com/algolia/docsearch-configs/pull/4693). I believe the scraper will re-run post PR merge? 
Thanks!

**Comment by shortcuts** [comment]
> I believe the scraper will re-run post PR merge? 

Exactly, please let me know how it goes!

**Comment by ujjawalpabreja99** [comment]
I'm afraid the results are still the same. 
Does the scraper redirect the URLs listed in `sitemap.xml`? `https://spaceweb.netlify.com` redirects to `https://spaceweb.netlify.app` for us, the former being listed in our sitemap.

**Comment by shortcuts** [comment]
> Does the scraper redirect the URLs listed in sitemap.xml? https://spaceweb.netlify.com redirects to https://spaceweb.netlify.app for us, the former being listed in our sitemap.

If only the `.app` is in the `start_urls`, the `.com` will be ignored, updating the sitemap would be the best.

I'm out of office so I can't test the results right now, but if you have your own Algolia app (free plan works), you can try it: https://docsearch.algolia.com/docs/run-your-own/

**Comment by ujjawalpabreja99** [comment]
Ah okay, I'll fix this in our sitemap! Most likely this is the bottleneck for us. Thanks for the prompt response!

**Comment by ujjawalpabreja99** [comment]
> If only the .app is in the start_urls, the .com will be ignored, updating the sitemap would be the best.

We've fixed this in our sitemap. Please let us know when the scraper re-runs so that we can check!
