### ISSUE TITLE
Wrong anchor applied to links of found entries

### ISSUE THREAD

**Issue by lubber-de** [algolia/docsearch-configs#883]
# Bug

## Current Behaviour

Algolia search does not seem to find the anchors to the found features on our site correctly.
In most cases it always adds `#toc` to the URL

### Example
- Visit https://fomantic-ui.com (desktop) and focus the Algolia Search Box at the top of the screen
- Search for `calendar`. Nearly every found entry will link to the `#toc` anchor, although there exists a proper anchor already

![image](https://user-images.githubusercontent.com/18379884/59196348-addbf080-8b8e-11e9-9198-c31a036327af.png)
Although there exists 
https://fomantic-ui.com/behaviors/form.html#handling-dates-from-calendars ,
it links to
https://fomantic-ui.com/behaviors/form.html#toc
instead

## What is the **expected** behaviour?
The appropriate anchor found by the search engine should be applied to the related link.

#### What have you tried to solve it?
- Search for `anchor` in github issues or docs page.

#### Any quick clues?
I guess, it's about selectors and probably nested anchor tags... @hammy2899: In case of feedback, please check our config accordingly
#570 might seem to be a similar issue

### Any other feedback / questions ?
Great Job on the Algolia Docs search 👍 😉

**Comment by s-pace** [comment]
Thank for the update, should be solved now thanks to b70af97

**Comment by lubber-de** [comment]
@s-pace Thank you, after re-indexing it unfortunately still does not work as expected. Now the links always got the `#example` anchor instead 😢 
![image](https://user-images.githubusercontent.com/18379884/59414912-cb919b80-8dc2-11e9-89d9-7314c721beca.png)

**Comment by s-pace** [comment]
@lubber-de your anchor needed some JS to be set, now it is perfectly done :)

**Comment by lubber-de** [comment]
@s-pace Thanks for the very fast response and fix 👍 ! 😎 
Interesting though: When i now search for `calendar` as before, the above mentioned link (seen in the previous screenshot) https://fomantic-ui.com/behaviors/form.html#handling-dates-from-calendars is not found anymore (only when i search for `from calendar` (or `form` of course)

**Comment by s-pace** [comment]
It is because we only display the top 5 most relevant results. It is here but hidden :)

**Comment by s-pace** [comment]
IMHO you should also display the search bar when you are inside the docs
![image](https://user-images.githubusercontent.com/32097720/59418133-ca636d00-8dc8-11e9-9016-c733b6b5fe2f.png)

**Comment by lubber-de** [comment]
> It is because we only display the top 5 most relevant results. It is here but hidden :)

Ah, ok. Thanks for clarification.
Out of curiousity: Is this behavior configurable (how many results to be displayed) per site? 

> IMHO you should also display the search bar when you are inside the docs

Yes, definately! We are currently working on that, but afaik we've got some rendering problems displaying the algolia widget inside the sidebar.. 🤔  @hammy2899 is working on it already 🙂

**Comment by s-pace** [comment]
Yes sure, check in our doc for hitPerPage
